### PR TITLE
Add option to manually set zIndex on DrawIO iFrame

### LINKED ISSUE #27: Dynamic Z-Index
For one of the templates I am using, the z-index for the header / sidebar is set to 1071, so it covers up the draw.io page (which is at 999).

While I could just fork this and increase the z-index, I imagine other people may run into this at some point. I was thinking about adding a config option to increase the z-index value as a style element on the iframe.

If I created a pull request for this, would it be welcome? Or is there a better way of handling that?

Thanks

### PR DESCRIPTION
**Pull request by SoarinFerret**
# Manually set zIndex on DrawIO iFrame

On the theme I am using, the navbar and sidebar both have higher z-Index values than draw.io. Instead of modifying the theme to fix or simply setting this plugin's iframe to a higher z-index, I added the option to set the z-index in the configuration settings.

I left the default value to still be 999, which is what the plugin sets normally, so default behavior will not change.

Here is a screenshot of the admin configuration page:

image

Please let me know if there is something you would like me to do differently - I am do not traditionally code with either PHP or JavaScript, so I'm sure there is some room for improvement.

Fixes #27

### CODE REVIEW

**Comment by lejmr** [comment]
Sounds like a fantastic improvement. Will check the pr ASAP

**Comment by lejmr** [comment]
Can you please adjust formatting? Seems the action.php contains all lines changed, but it does not seem you changed everything :-) Thanks

**Comment by SoarinFerret** [comment]
My bad, looks like my editor converted the line endings from CRLF to just LF, I'll change it back

**Comment by lejmr** [comment]
Thank you for contribution

**Pull request merged**
