### PR TITLE
add possibility to use svg image

### PR DESCRIPTION
**Pull request by Vincent31Fr**
This feature add possibility to use svg image as well as png. the differentiation is made on file extension

### CODE REVIEW

**Comment by lejmr** [comment]
Thanks for a very interesting contribution. 

Can you please update this code, so it:
 * uses the configuration for selection of default format
 * when no extension is specified the default format is selected

Maybe it is just problem with Chrome and Firefox, but when I draw an image and close the editor I can see the diagram (even I can click on weblink). However, when reload the page my browser gives me an icon of a broken image.. thanks for looking at it,

**Comment by Vincent31Fr** [comment]
OK for your 1st point I think it is a good idea. I could add a default conf which would also be taken into account in the toolbar.

For your second point, I have a problem with not having the extension in the media name, especially when changing the default extension.
We could end up with 2 medias with the same name (with a different extension: for example diagram1.png and diagram1.svg). But in the wiki page, there is only {{drawio> diagram1}}. In this case, it is not possible to know which one to use.

Maybe you have a better idea on how to manage it but it think that is not compatible with default configuration.

I forgot to mention that to be able to use the svg images, you need to install the plugin [svgembed](https://www.dokuwiki.org/plugin:svgembed)

**Comment by Vincent31Fr** [comment]
however, what we can do (to limit the impact on existing wikis which already use this plugin) is not to have a modifiable "default configuration" but if in the wiki page, the name of the image does not have an extension, it is considered to be PNG (basic plugin with no other plugin required). 
we can also add a configuration variable so that through the toolbar, we can select one of the possible extentions (manually set in admin panel and depending on the requiered plugins installed)

What do you think about that ?

**Comment by lejmr** [comment]
As I dont know how to quota and answer only certain parts of you answers, I will try to embed the answer into a "flow" describing my view while tackling your struggles :-) 

Here we go..

* Lets use configuration option where we state the default extension: png/svg .. lets say `svg` is the default for the rest of the text
* I create a new drawing `{{drawio> diagram1}}` when I click on save diagram1.svg file is created.

After some time I want to add a new diagram, but for some reason I want it to be saved as .png file, and as I am in the same space and I am forgetful 
* I create a new drawing `{{drawio> diagram1.png}}` when I click on save diagram1.png file is created.
* I am having two diagram1 files in the same directory, but with two different extensions

Good news is both wiki pages depict the right images because `{{drawio> diagram1}}` uses configuration to determine `svg` as the default format.

After some more time I decide I want to have my default format be `png`. 
* I go to configuration section and override `svg` to `png`
* The first wiki page shows me the same image as the second wiki page, i.e. `diagram1.png` .. 
* I scratch my forehead, and modify `{{drawio> diagram1}}` to `{{drawio> diagram1.svg}}` on the first wiki page.
* Potentially, I can even modify `{{drawio> diagram1.png}}` to `{{drawio> diagram1}}`, as both should be showing the same image.

What do you think about that?

**Comment by Vincent31Fr** [comment]
Your proposal may be acceptable when there are few pages to edit ! But imagine a big wiki with a lot of images already created with your plugin! \
It does not seem very proper to me to have to update all the pages if a configuration change is made. I prefer don't break existing wikis already in production.
In addition, the default png format (in the code, therefore not modifiable via the configuration) is compatible with almost all web browsers.

**Comment by lejmr** [comment]
Are you proposing to have png as a default, and only if you want to have svg, you add svg extension to the name, e.g. `{{drawio> diagram1.svg}}`? If so, I am ok with that.

**Comment by Vincent31Fr** [comment]
yes it's that: 

- no extension = png 
- png extension = png
- svg extension = svg
for other extension, it's when I will have time ;-)

**Comment by lejmr** [comment]
OK, then go ahead :-) Looking forward to the contribution :-)

**Comment by Vincent31Fr** [comment]
Done !

**Comment by lejmr** [comment]
Thanks for your work, but there are a few things which I find confusing. I have a vanilla installation with your master branch version and svgembed plugin installed. Technically, I am running a recent bitnami/dokuwiki docker container.

- When I click on drawio icon, I get `{{drawio>diagram1.png}}` .. I think there should be no extension
- When I enabled svg (png, svg in configuration), and I click on `svg` drawio image I get `{{drawio>diagram1. svg}}`. Subsequently, the drawio javascript editor is not working. I think you should trim the options. Some people might be adding whitespaces
- Even with svgembed plugin installed, after svg diagram is saved and I do reload the page, the svg diagram is not pictured.

image

for
 
```
fdsfdsfs

{{drawio>diagram1.png}}

{{drawio>diagram1.svg}}

{{drawio>diagram2.svg}}
{{drawio>diagram2}}
```

**Comment by Vincent31Fr** [comment]
> * When I click on drawio icon, I get `{{drawio>diagram1.png}}` .. I think there should be no extension

Better to have a fully qualified media name. Therefore, the new diagram created (via the button of the toolbar) uses the png extension. you can manually remove the extension if you want

> * When I enabled svg (png, svg in configuration), and I click on `svg` drawio image I get `{{drawio>diagram1. svg}}`. Subsequently, the drawio javascript editor is not working. I think you should trim the options. Some people might be adding whitespaces

Ok fix in my last commit

> * Even with svgembed plugin installed, after svg diagram is saved and I do reload the page, the svg diagram is not pictured.

Have you add this "svg     image/svg+xml" in a conf/mime.local.conf file ? See [Uploading SVG files via Media Manager](https://www.dokuwiki.org/plugin:svgembed#Uploading_SVG_files_via_Media_Manager) section

**Comment by ben-nida** [comment]
Hi, sorry to bother, were there any updates to this? I'd love to use this feature.

**Pull request merged**
